// auto-generated by configen
// to add or remove properties, edit the mapping file: './AppEnvironment.map'.
// README: https://github.com/theappbusiness/ConfigGenerator/blob/master/README.md

import Foundation

class AppEnvironment {

  static let entryPointURL: URL = URL(string: "http://example.com/production")!

  static let enableFileSharing: Bool = true

  static let environment: Environment = .Production

  static let dictionary: [String: Any] = ["number": 1, "double": 1.5, "bool": false, "string": "hello"]

  static let analyticsKey: String = "haf6d9fha8v56abs"

  static let adUnitPrefix: String = "production_ad_unit"

  static let retryCount: Int = 4

}

